#!/bin/bash

# Read lines from input.txt and assign to variables
readarray -t lines < input.txt

file1="${lines[0]}"
file2="${lines[1]}"
file3="${lines[2]}"

# Run the Java program with the arguments
java -jar target/lightdb-1.0.0-jar-with-dependencies.jar "$file1" "$file2" "$file3"
