#!/bin/bash

# Loop through queries 1 to 9
for ((i=1; i<=12; i++)); do
    # Run the Java command with the appropriate query file
    java -jar target/lightdb-1.0.0-jar-with-dependencies.jar samples/db samples/input/query$i.sql samples/output/query$i.csv
done
